# Generated by Django 3.2.13 on 2022-10-21 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='releasedate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='runningtime',
            field=models.IntegerField(default=50),
        ),
    ]
